# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Justin/Documents/4th School Year/Fall 2016 Semester/EE178/Vivado Projects/EE178_Lab_6/EE178_Lab_6.srcs/sources_1/ip/framebuffer/framebuffer.xci
# IP: The module: 'framebuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Justin/Documents/4th School Year/Fall 2016 Semester/EE178/Vivado Projects/EE178_Lab_6/EE178_Lab_6.srcs/sources_1/ip/framebuffer/framebuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'framebuffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Justin/Documents/4th School Year/Fall 2016 Semester/EE178/Vivado Projects/EE178_Lab_6/EE178_Lab_6.srcs/sources_1/ip/framebuffer/framebuffer.xci
# IP: The module: 'framebuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Justin/Documents/4th School Year/Fall 2016 Semester/EE178/Vivado Projects/EE178_Lab_6/EE178_Lab_6.srcs/sources_1/ip/framebuffer/framebuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'framebuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
